MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
#  WEIGHT: "./kiktech_mobileNet_V3_weight_progress_1/model_final.pth"
  BACKBONE:
    CONV_BODY: "MobileNetV3"
  RETINANET:
    NUM_CLASSES: 12
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_KEYPOINT_HEAD:
    NUM_CLASSES: 12
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPNXconv1fcFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 12
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    CATEGORY_NUM: 0

  MASK_ON: True
DATASETS:
  TRAIN: ("skyeye_cocostyle_train", "skyeye_cocostyle_val",)
  TEST: ("skyeye_cocostyle_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (48000, 64000)
  MAX_ITER: 288000
  CHECKPOINT_PERIOD: 36000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./skyeye_maskrcnn_mobileNet_V3_weight_progress_3/"
DTYPE: "float16"